language: ruby
rvm:
  - 2.3.3
before_script:
  - npm install
  - bundle install
  - bundle exec jekyll build
script: npm run build

branches:
  except:
    - gh-pages

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#   keep-history: true
#   on:
#     branch: master
