---
##### seo #####
title: The Independent Group
description: >
             The Independent Group (US) is a multidisciplinary design practice
             that collaborates with a diverse group of individuals, groups,
             organizations, and commercial clients to create distinctive work
             that establishes meaningful, lasting connections with their audiences.
             We are dedicated to forward-thinking initiatives that promote education,
             sustainability, and positive social impact.
url:
twitter:
  username:
logo:
social:
  name: The Independent Group
  links:
    - https://www.instagram.com/theindependentgroup/
    - https://github.com/theindependentgroup
webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234

##### etc #####
ga_analytics: UA-96203809-1
imgix:
  source: imgix.net
timezone: America/New_York

##### defaults #####

##### collections #####
collections:
  projects:
    title: Projects
    output: false

##### jekyll #####
permalink: pretty
exclude:
- "*.config"
- assets/src
- ".gitignore"
- Gulpfile.js
- node_modules
- package.json
- README*
- tools/
- webpack.config.js
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll/imgix
